"""avatar

Revision ID: 1bb63a5ee9e
Revises: 1ec6458ac43
Create Date: 2015-12-15 14:56:45.755095

"""

# revision identifiers, used by Alembic.
revision = '1bb63a5ee9e'
down_revision = '1ec6458ac43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
