"""confirmation

Revision ID: 27585dd61da
Revises: 4fae646247f
Create Date: 2015-12-14 11:16:53.025464

"""

# revision identifiers, used by Alembic.
revision = '27585dd61da'
down_revision = '4fae646247f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
