"""version

Revision ID: 4f5df399a94
Revises: 4537c34d6ef
Create Date: 2015-12-28 10:49:49.626132

"""

# revision identifiers, used by Alembic.
revision = '4f5df399a94'
down_revision = '4537c34d6ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('body', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('body_html', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('upvotes', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('downvotes', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('ranking', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_answers_version_end_transaction_id'), 'answers_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_answers_version_operation_type'), 'answers_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_answers_version_ranking'), 'answers_version', ['ranking'], unique=False)
    op.create_index(op.f('ix_answers_version_timestamp'), 'answers_version', ['timestamp'], unique=False)
    op.create_index(op.f('ix_answers_version_transaction_id'), 'answers_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_answers_version_transaction_id'), table_name='answers_version')
    op.drop_index(op.f('ix_answers_version_timestamp'), table_name='answers_version')
    op.drop_index(op.f('ix_answers_version_ranking'), table_name='answers_version')
    op.drop_index(op.f('ix_answers_version_operation_type'), table_name='answers_version')
    op.drop_index(op.f('ix_answers_version_end_transaction_id'), table_name='answers_version')
    op.drop_table('answers_version')
    ### end Alembic commands ###
