"""actor id

Revision ID: cbf66625da
Revises: 9bdbd01a7b
Create Date: 2015-12-28 15:43:56.948016

"""

# revision identifiers, used by Alembic.
revision = 'cbf66625da'
down_revision = '9bdbd01a7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows_version')
    op.add_column('activity', sa.Column('actor_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'actor_id')
    op.create_table('follows_version',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('followed_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', 'transaction_id')
    )
    ### end Alembic commands ###
